export const arrayOfKeys = [
  {
    eventWhich: 27,
    type: 'control',
    className: 'keys, esc-key',
    capsText: 'Esc',
    text: 'Esc',
    code: 'Escape',
    textRu: 'Esc',
  },
  {
    eventWhich: 192,
    type: 'letter',
    className: 'keys',
    capsText: '`',
    text: '`',
    code: 'Backquote',
    textRu: 'Ё',
  },
  {
    eventWhich: 49,
    type: 'number',
    className: 'keys',
    capsText: '1',
    text: '1',
    code: 'Digit1',
    textRu: '1',
  },
  {
    eventWhich: 50,
    type: 'number',
    className: 'keys',
    capsText: '2',
    text: '2',
    code: 'Digit2',
    textRu: '2',
  },
  {
    eventWhich: 51,
    type: 'number',
    className: 'keys',
    capsText: '3',
    text: '3',
    code: 'Digit3',
    textRu: '3',
  },
  {
    eventWhich: 52,
    type: 'number',
    className: 'keys',
    capsText: '4',
    text: '4',
    code: 'Digit4',
    textRu: '4',
  },
  {
    eventWhich: 53,
    type: 'number',
    className: 'keys',
    capsText: '5',
    text: '5',
    code: 'Digit5',
    textRu: '5',
  },
  {
    eventWhich: 54,
    type: 'number',
    className: 'keys',
    capsText: '6',
    text: '6',
    code: 'Digit6',
    textRu: '6',
  },
  {
    eventWhich: 55,
    type: 'number',
    className: 'keys',
    capsText: '7',
    text: '7',
    code: 'Digit7',
    textRu: '7',
  },
  {
    eventWhich: 56,
    type: 'number',
    className: 'keys',
    capsText: '8',
    text: '8',
    code: 'Digit8',
    textRu: '8',
  },
  {
    eventWhich: 57,
    type: 'number',
    className: 'keys',
    capsText: '9',
    text: '9',
    code: 'Digit9',
    textRu: '9',
  },
  {
    eventWhich: 48,
    type: 'number',
    className: 'keys',
    capsText: '0',
    text: '0',
    code: 'Digit0',
    textRu: '0',
  },
  {
    eventWhich: 189,
    type: 'letter',
    className: 'keys',
    capsText: '-',
    text: '-',
    code: 'Minus',
    textRu: '-',
  },
  {
    eventWhich: 187,
    type: 'letter',
    className: 'keys',
    capsText: '=',
    text: '=',
    code: 'Equal',
    textRu: '=',
  },
  {
    eventWhich: 8,
    type: 'backspace',
    className: 'keys, backspace-key',
    capsText: 'Backspace',
    text: 'Backspace',
    code: 'Backspace',
    textRu: 'Backspace',
  },
  {
    eventWhich: 9,
    type: 'tab',
    className: 'keys, tab-key',
    capsText: 'Tab',
    text: 'Tab',
    code: 'Tab',
    textRu: 'Tab',
  },
  {
    eventWhich: 81,
    type: 'letter',
    className: 'keys',
    capsText: 'Q',
    text: 'q',
    code: 'KeyQ',
    textRu: 'Й',
  },
  {
    eventWhich: 87,
    type: 'letter',
    className: 'keys',
    capsText: 'W',
    text: 'w',
    code: 'KeyW',
    textRu: 'Ц',
  },
  {
    eventWhich: 69,
    type: 'letter',
    className: 'keys',
    capsText: 'E',
    text: 'e',
    code: 'KeyE',
    textRu: 'У',
  },
  {
    eventWhich: 82,
    type: 'letter',
    className: 'keys',
    capsText: 'R',
    text: 'r',
    code: 'KeyR',
    textRu: 'К',
  },
  {
    eventWhich: 84,
    type: 'letter',
    className: 'keys',
    capsText: 'T',
    text: 't',
    code: 'KeyT',
    textRu: 'Е',
  },
  {
    eventWhich: 89,
    type: 'letter',
    className: 'keys',
    capsText: 'Y',
    text: 'y',
    code: 'KeyY',
    textRu: 'Н',
  },
  {
    eventWhich: 85,
    type: 'letter',
    className: 'keys',
    capsText: 'U',
    text: 'u',
    code: 'KeyU',
    textRu: 'Г',
  },
  {
    eventWhich: 73,
    type: 'letter',
    className: 'keys',
    capsText: 'I',
    text: 'i',
    code: 'KeyI',
    textRu: 'Ш',
  },
  {
    eventWhich: 79,
    type: 'letter',
    className: 'keys',
    capsText: 'O',
    text: 'o',
    code: 'KeyO',
    textRu: 'Щ',
  },
  {
    eventWhich: 80,
    type: 'letter',
    className: 'keys',
    capsText: 'P',
    text: 'p',
    code: 'KeyP',
    textRu: 'З',
  },
  {
    eventWhich: 219,
    type: 'letter',
    className: 'keys',
    capsText: '[',
    text: '[',
    code: 'BracketLeft',
    textRu: 'Х',
  },
  {
    eventWhich: 221,
    type: 'letter',
    className: 'keys',
    capsText: ']',
    text: ']',
    code: 'BracketRight',
    textRu: 'Ъ',
  },
  {
    eventWhich: 220,
    type: 'letter',
    className: 'keys, slash-key',
    capsText: '\\',
    text: '\\',
    code: 'Backslash',
    textRu: '\\',
  },
  {
    eventWhich: 46,
    type: 'control',
    className: 'keys, del-key',
    capsText: 'Del',
    text: 'Del',
    code: 'Delete',
    textRu: 'Del',
  },
  {
    eventWhich: 20,
    type: 'capslock',
    className: 'keys, capslock-key',
    capsText: 'Caps Lock',
    text: 'Caps Lock',
    code: 'CapsLock',
    textRu: 'Caps Lock',
  },
  {
    eventWhich: 65,
    type: 'letter',
    className: 'keys',
    capsText: 'A',
    text: 'a',
    code: 'KeyA',
    textRu: 'Ф',
  },
  {
    eventWhich: 83,
    type: 'letter',
    className: 'keys',
    capsText: 'S',
    text: 's',
    code: 'KeyS',
    textRu: 'Ы',
  },
  {
    eventWhich: 68,
    type: 'letter',
    className: 'keys',
    capsText: 'D',
    text: 'd',
    code: 'KeyD',
    textRu: 'В',
  },
  {
    eventWhich: 70,
    type: 'letter',
    className: 'keys',
    capsText: 'F',
    text: 'f',
    code: 'KeyF',
    textRu: 'А',
  },
  {
    eventWhich: 71,
    type: 'letter',
    className: 'keys',
    capsText: 'G',
    text: 'g',
    code: 'KeyG',
    textRu: 'А',
  },
  {
    eventWhich: 72,
    type: 'letter',
    className: 'keys',
    capsText: 'H',
    text: 'h',
    code: 'KeyH',
    textRu: 'Р',
  },
  {
    eventWhich: 74,
    type: 'letter',
    className: 'keys',
    capsText: 'J',
    text: 'j',
    code: 'KeyJ',
    textRu: 'О',
  },
  {
    eventWhich: 75,
    type: 'letter',
    className: 'keys',
    capsText: 'K',
    text: 'k',
    code: 'KeyK',
    textRu: 'Л',
  },
  {
    eventWhich: 76,
    type: 'letter',
    className: 'keys',
    capsText: 'L',
    text: 'l',
    code: 'KeyL',
    textRu: 'Д',
  },
  {
    eventWhich: 186,
    type: 'letter',
    className: 'keys',
    capsText: ';',
    text: ';',
    code: 'Semicolon',
    textRu: 'Ж',
  },
  {
    eventWhich: 222,
    type: 'letter',
    className: 'keys',
    capsText: "'",
    text: "'",
    code: 'Quote',
    textRu: 'Э',
  },
  {
    eventWhich: 13,
    type: 'enter',
    className: 'keys, enter-key',
    capsText: 'Enter',
    text: 'Enter',
    code: 'Enter',
    textRu: 'Enter',
  },
  {
    eventWhich: 16,
    type: 'control',
    className: 'keys, shift-key, shift-left',
    capsText: 'Shift',
    text: 'Shift',
    code: 'ShiftLeft',
    textRu: 'Ё',
  },
  {
    eventWhich: 90,
    type: 'letter',
    className: 'keys',
    capsText: 'Z',
    text: 'z',
    code: 'KeyZ',
    textRu: 'Я',
  },
  {
    eventWhich: 88,
    type: 'letter',
    className: 'keys',
    capsText: 'X',
    text: 'x',
    code: 'KeyX',
    textRu: 'Ч',
  },
  {
    eventWhich: 67,
    type: 'letter',
    className: 'keys',
    capsText: 'C',
    text: 'c',
    code: 'KeyC',
    textRu: 'С',
  },
  {
    eventWhich: 86,
    type: 'letter',
    className: 'keys',
    capsText: 'V',
    text: 'v',
    code: 'KeyV',
    textRu: 'М',
  },
  {
    eventWhich: 66,
    type: 'letter',
    className: 'keys',
    capsText: 'B',
    text: 'b',
    code: 'KeyB',
    textRu: 'И',
  },
  {
    eventWhich: 78,
    type: 'letter',
    className: 'keys',
    capsText: 'N',
    text: 'n',
    code: 'KeyN',
    textRu: 'Т',
  },
  {
    eventWhich: 77,
    type: 'letter',
    className: 'keys',
    capsText: 'M',
    text: 'm',
    code: 'KeyM',
    textRu: 'Ь',
  },
  {
    eventWhich: 188,
    type: 'letter',
    className: 'keys',
    capsText: ',',
    text: ',',
    code: 'Comma',
    textRu: 'Б',
  },
  {
    eventWhich: 190,
    type: 'letter',
    className: 'keys',
    capsText: '.',
    text: '.',
    code: 'Period',
    textRu: 'Ю',
  },
  {
    eventWhich: 191,
    type: 'letter',
    className: 'keys',
    capsText: '/',
    text: '/',
    code: 'Slash',
    textRu: '.',
  },
  {
    eventWhich: 38,
    type: 'arrow',
    className: 'keys, up-arrow-key',
    capsText: '↑',
    text: '↑',
    code: 'ArrowUp',
    textRu: '↑',
  },
  {
    eventWhich: 16,
    type: 'control',
    className: 'keys, shift-key, shift-right',
    capsText: 'Shift',
    text: 'Shift',
    code: 'ShiftRight',
    textRu: 'Shift',
  },
  {
    eventWhich: 17,
    type: 'control',
    className: 'keys, ctrl-key, ctrl-left',
    capsText: 'Ctrl',
    text: 'Ctrl',
    code: 'ControlLeft',
    textRu: 'Ctrl',
  },
  {
    eventWhich: 255,
    type: 'control',
    className: 'keys, win-key',
    capsText: 'Win',
    text: 'Win',
    code: 'WakeUp',
    textRu: 'Win',
  },
  {
    eventWhich: 18,
    type: 'control',
    className: 'keys, alt-key, alt-left',
    capsText: 'Alt',
    text: 'Alt',
    code: 'AltLeft',
    textRu: 'Alt',
  },
  {
    eventWhich: 32,
    type: 'letter',
    className: 'keys, space-key',
    capsText: ' ',
    text: ' ',
    code: 'Space',
    textRu: ' ',
  },
  {
    eventWhich: 18,
    type: 'control',
    className: 'keys, alt-key, alt-right',
    capsText: 'Alt',
    text: 'Alt',
    code: 'AltRight',
    textRu: 'Alt',
  },
  {
    eventWhich: 37,
    type: 'arrow',
    className: 'keys, left-arrow-key',
    capsText: '←',
    text: '←',
    code: 'ArrowLeft',
    textRu: '←',
  },
  {
    eventWhich: 40,
    type: 'arrow',
    className: 'keys, down-arrow-key',
    capsText: '↓',
    text: '↓',
    code: 'ArrowDown',
    textRu: '↓',
  },
  {
    eventWhich: 39,
    type: 'arrow',
    className: 'keys, right-arrow-key',
    capsText: '→',
    text: '→',
    code: 'ArrowRight',
    textRu: '→',
  },
  {
    eventWhich: 17,
    type: 'control',
    className: 'keys, ctrl-key, ctrl-right',
    capsText: 'Ctrl',
    text: 'Ctrl',
    code: 'ControlRight',
    textRu: 'Ctrl',
  },
];
