export const arrayOfKeys = [
  {
    eventWhich: 27,
    type: "div",
    className: "keys",
    text: "Esc",
  },
  {
    eventWhich: 192,
    type: "div",
    className: "keys",
    text: "`",
  },
  {
    eventWhich: 49,
    type: "div",
    className: "keys",
    text: "1",
  },
  {
    eventWhich: 50,
    type: "div",
    className: "keys",
    text: "2",
  },
  {
    eventWhich: 51,
    type: "div",
    className: "keys",
    text: "3",
  },
  {
    eventWhich: 52,
    type: "div",
    className: "keys",
    text: "4",
  },
  {
    eventWhich: 53,
    type: "div",
    className: "keys",
    text: "5",
  },
  {
    eventWhich: 54,
    type: "div",
    className: "keys",
    text: "6",
  },
  {
    eventWhich: 55,
    type: "div",
    className: "keys",
    text: "7",
  },
  {
    eventWhich: 56,
    type: "div",
    className: "keys",
    text: "8",
  },
  {
    eventWhich: 57,
    type: "div",
    className: "keys",
    text: "9",
  },
  {
    eventWhich: 48,
    type: "div",
    className: "keys",
    text: "0",
  },
  {
    eventWhich: 189,
    type: "div",
    className: "keys",
    text: "-",
  },
  {
    eventWhich: 187,
    type: "div",
    className: "keys",
    text: "=",
  },
  {
    eventWhich: 8,
    type: "div",
    className: "keys",
    text: "Backspace",
  },
  {
    eventWhich: 9,
    type: "div",
    className: "keys",
    text: "Tab",
  },
  {
    eventWhich: 81,
    type: "div",
    className: "keys",
    text: "Q",
  },
  {
    eventWhich: 87,
    type: "div",
    className: "keys",
    text: "W",
  },
  {
    eventWhich: 69,
    type: "div",
    className: "keys",
    text: "E",
  },
  {
    eventWhich: 82,
    type: "div",
    className: "keys",
    text: "R",
  },
  {
    eventWhich: 84,
    type: "div",
    className: "keys",
    text: "T",
  },
  {
    eventWhich: 89,
    type: "div",
    className: "keys",
    text: "Y",
  },
  {
    eventWhich: 85,
    type: "div",
    className: "keys",
    text: "U",
  },
  {
    eventWhich: 73,
    type: "div",
    className: "keys",
    text: "I",
  },
  {
    eventWhich: 79,
    type: "div",
    className: "keys",
    text: "O",
  },
  {
    eventWhich: 80,
    type: "div",
    className: "keys",
    text: "P",
  },
  {
    eventWhich: 219,
    type: "div",
    className: "keys",
    text: "[",
  },
  {
    eventWhich: 221,
    type: "div",
    className: "keys",
    text: "]",
  },
  {
    eventWhich: 220,
    type: "div",
    className: "keys",
    text: "\\",
  },
  {
    eventWhich: 20,
    type: "div",
    className: "keys",
    text: "Caps Lock",
  },
  {
    eventWhich: 65,
    type: "div",
    className: "keys",
    text: "A",
  },
  {
    eventWhich: 83,
    type: "div",
    className: "keys",
    text: "S",
  },
  {
    eventWhich: 68,
    type: "div",
    className: "keys",
    text: "D",
  },
  {
    eventWhich: 70,
    type: "div",
    className: "keys",
    text: "F",
  },
  {
    eventWhich: 71,
    type: "div",
    className: "keys",
    text: "G",
  },
  {
    eventWhich: 72,
    type: "div",
    className: "keys",
    text: "H",
  },
  {
    eventWhich: 74,
    type: "div",
    className: "keys",
    text: "J",
  },
  {
    eventWhich: 75,
    type: "div",
    className: "keys",
    text: "K",
  },
  {
    eventWhich: 76,
    type: "div",
    className: "keys",
    text: "L",
  },
  {
    eventWhich: 186,
    type: "div",
    className: "keys",
    text: ";",
  },
  {
    eventWhich: 222,
    type: "div",
    className: "keys",
    text: "'",
  },
  {
    eventWhich: 13,
    type: "div",
    className: "keys",
    text: "Enter",
  },
  {
    eventWhich: 16,
    type: "div",
    className: "keys",
    text: "Shift",
  },
  {
    eventWhich: 90,
    type: "div",
    className: "keys",
    text: "Z",
  },
  {
    eventWhich: 88,
    type: "div",
    className: "keys",
    text: "X",
  },
  {
    eventWhich: 67,
    type: "div",
    className: "keys",
    text: "C",
  },
  {
    eventWhich: 86,
    type: "div",
    className: "keys",
    text: "V",
  },
  {
    eventWhich: 66,
    type: "div",
    className: "keys",
    text: "B",
  },
  {
    eventWhich: 78,
    type: "div",
    className: "keys",
    text: "N",
  },
  {
    eventWhich: 77,
    type: "div",
    className: "keys",
    text: "M",
  },
  {
    eventWhich: 188,
    type: "div",
    className: "keys",
    text: ",",
  },
  {
    eventWhich: 190,
    type: "div",
    className: "keys",
    text: ".",
  },
  {
    eventWhich: 191,
    type: "div",
    className: "keys",
    text: "/",
  },
  {
    eventWhich: 38,
    type: "div",
    className: "keys",
    text: "↑",
  },
  {
    eventWhich: 16,
    type: "div",
    className: "keys",
    text: "Shift",
  },
  {
    eventWhich: 17,
    type: "div",
    className: "keys",
    text: "Ctrl",
  },
  {
    eventWhich: 255,
    type: "div",
    className: "keys",
    text: "Win",
  },
  {
    eventWhich: 18,
    type: "div",
    className: "keys",
    text: "Alt",
  },
  {
    eventWhich: 32,
    type: "div",
    className: "keys",
    text: " ",
  },
  {
    eventWhich: 18,
    type: "div",
    className: "keys",
    text: "Alt",
  },
  {
    eventWhich: 37,
    type: "div",
    className: "keys",
    text: "←",
  },
  {
    eventWhich: 40,
    type: "div",
    className: "keys",
    text: "↓",
  },
  {
    eventWhich: 39,
    type: "div",
    className: "keys",
    text: "→",
  },
  {
    eventWhich: 17,
    type: "div",
    className: "keys",
    text: "Ctrl",
  },
];
